// src/Components/constants/index.ts
export const ServiceData = [
  {
    title: "FLATKÖKUR",
    content: "Hver vill ekki góða flatköku. Ummm, hvað þær eru góðar.",
    Image: "/Flatkaka.png",
    ingredients:
      "Hveiti, vatn, rúgmjöl, haframjöl, repjuolía, salt, lyftiefni (E450, E500), rotvarnarefni (E282), kókosolía.\n\nHeimildir: ÍSGEM og upplýsingablöð frá framleiðanda.\n\nUnnið samkvæmt reglugerð nr. 1294/2014 (EU nr. 1169/2011)\nHeimildir: ÍSGEM og upplýsingablöð frá framleiðanda\n\n– Næringargildi eru afrúnnuð samkvæmt leiðbeiningum frá MAST um næringaryfirlýsingu á matvælum og skulu notuð þannig við merkingar.\n\n– Ekki er skylt að merkja trefjar samkv. reglugerð en þær mega koma fram sem viðbótaupplýsingar.",
    kj: "989",
    kkal: "236",
    Fita: "2,5",
    fitusyra: "0,3",
    kolvetni: "44,9",
    sykur: "0,5",
    protein: "6,4",
    salt: "1,2",
  },
  {
    title: "FJALLAGRASAKÖKUR",
    content:
      "Þessar eru eins og hefðbundnu sívinsælu flatkökurnar okkar en við bætum í þær fjallagrösum sem gefa þeim einstakt bragð.",
    Image: "/Fjallagrasakaka.png",
    ingredients:
      "Hveiti, vatn, haframjöl, rúgmjöl, fjallagrös (2%), repjuolía, salt, lyftiefni (E450, E500), rotvarnarefni(E282), kókosolía.\n\nHeimildir: ÍSGEM og upplýsingablöð frá framleiðanda.\n\nUnnið samkvæmt reglugerð nr. 1294/2014 (EU nr. 1169/2011)\nHeimildir: ÍSGEM og upplýsingablöð frá framleiðanda\n\n– Næringargildi eru afrúnnuð samkvæmt leiðbeiningum frá MAST um næringaryfirlýsingu á matvælum og skulu notuð þannig við merkingar.\n\n– Ekki er skylt að merkja trefjar samkv. reglugerð en þær mega koma fram sem viðbótaupplýsingar.",
    kj: "966",
    kkal: "231",
    Fita: "2,4",
    fitusyra: "0,3",
    kolvetni: "43,3",
    sykur: "0,5",
    protein: "6,2",
    salt: "1,2",
  },
  {
    title: "KLEINUR",
    content:
      "Nýbakaðar kleinur og mjólk, hvað er betra en það? Ekki mikið getum við sagt ykkur.",
    Image: "/Kleinur.png",
    ingredients:
      "Hveiti (hveiti, maltað bygg, mjölmeðhöndlunarefni (E300), ensím), súrmjólk, sykur, vatn, egg, smjörlíki (pálma-, repju- og kókosolía, vatn, salt, ýruefni (E471, E322 (sólblóma), E475), undanrennuduft, rotvarnarefni (E202, E200, E330), bragðefni, þrávarnarefni (E306, E304)), lyftiefni (E450, E500), mysuduft, mjólkurduft, glúkósasíróp, ýruefni (E471), mjólkurprótein, salt, kekkjavarnarefni (E535), kardimommudropar (vatn, alkóhól, bragðefni).\n\nHeimildir: ÍSGEM og upplýsingablöð frá framleiðanda.\n\nUnnið samkvæmt reglugerð nr. 1294/2014 (EU nr. 1169/2011)\nHeimildir: ÍSGEM og upplýsingablöð frá framleiðanda\n\n– Næringargildi eru afrúnnuð samkvæmt leiðbeiningum frá MAST um næringaryfirlýsingu á matvælum og skulu notuð þannig við merkingar.\n\n– Ekki er skylt að merkja trefjar samkv. reglugerð en þær mega koma fram sem viðbótaupplýsingar.",
    kj: "1238",
    kkal: "296",
    Fita: "6",
    fitusyra: "2,5",
    kolvetni: "50,9",
    sykur: "14",
    protein: "7,7",
    salt: "1,6",
  },
  {
    title: "RÚGBRAUÐ",
    content: "Góður þrumari, flottur í kaffiboðinu",
    Image: "/Rugbraud.png",
    ingredients:
      "Vatn, rúgmjöl, heilhveiti (heilhveiti, mjölmeðhöndlunarefni (E300)), sykur, púðursykur, salt, kekkjavarnarefni (E535), undanrennuduft, matarsódi (lyftiefni (E500)), súrmjólk, hveiti, sýra (E330, E270), bindiefni (E516), sýrustillir (E263), pálmolía, ýruefni (E471).\n\nHeimildir: ÍSGEM og upplýsingablöð frá framleiðanda.\n\nUnnið samkvæmt reglugerð nr. 1294/2014 (EU nr. 1169/2011)\nHeimildir: ÍSGEM og upplýsingablöð frá framleiðanda\n\n– Næringargildi eru afrúnnuð samkvæmt leiðbeiningum frá MAST um næringaryfirlýsingu á matvælum og skulu notuð þannig við merkingar.\n\n– Ekki er skylt að merkja trefjar samkv. reglugerð en þær mega koma fram sem viðbótaupplýsingar.",
    kj: "953",
    kkal: "228",
    Fita: "0,8",
    fitusyra: "0,3",
    kolvetni: "48,9",
    sykur: "18",
    protein: "2,3",
    salt: "2",
  },
  {
    title: "SNÚÐAR",
    content: "Klassískir kanil snúðar.",
    Image: "/Snudar.png",
    ingredients:
      "Hveiti, sykur, smjörlíki (pálmaolía, repjuolía, vatn, salt, sýra (E300), ýruefni (E471), þrávarnarefni (E306, E304), bragðefni), egg, sulta (rabbabari (45%), sykur, vatn, bindiefni (E440), rotvarnarefni (E211)), lyftiefni (E450, E500), kanill.\n\nHeimildir: ÍSGEM og upplýsingablöð frá framleiðanda.\n\nUnnið samkvæmt reglugerð nr. 1294/2014 (EU nr. 1169/2011)\nHeimildir: ÍSGEM og upplýsingablöð frá framleiðanda\n\n– Næringargildi eru afrúnnuð samkvæmt leiðbeiningum frá MAST um næringaryfirlýsingu á matvælum og skulu notuð þannig við merkingar.\n\n– Ekki er skylt að merkja trefjar samkv. reglugerð en þær mega koma fram sem viðbótaupplýsingar.",
    kj: "1911",
    kkal: "457",
    Fita: "21",
    fitusyra: "10",
    kolvetni: "60,2",
    sykur: "26,5",
    protein: "5,8",
    salt: "0,9",
  },
];
